// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ingenium.Framework.Core.Data.Models;

public partial class Product
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal Price { get; set; }

    public int? CategoryId { get; set; }

    public virtual ICollection<CartProduct> CartProduct { get; set; } = new List<CartProduct>();

    public virtual Category Category { get; set; }
}