<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ACME.CartCustom.Domain\ACME.CartCustom.Domain.csproj" />
    <ProjectReference Include="..\Ingenium.Framework.Cart.Infrastructure\Ingenium.Framework.Cart.Infrastructure.csproj" />
    <ProjectReference Include="..\Ingenium.Framework.Core.Data\Ingenium.Framework.Core.Data.csproj" />
  </ItemGroup>

</Project>
